version: '3.1'

services:
  mysql-8.0.29-debian:
    image: mysql:8.0.29-debian
    container_name: mysql_db_ufes_delivery
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
      - TZ=America/Sao_Paulo
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend_python

  python-3.10.4-alpine3.15:
    build: .
    container_name: python_ufes_delivery
    restart: always
    depends_on:
      - "mysql-8.0.29-debian"
    ports:
      - $APP_PORT:5000
    networks:
      - backend_python

networks:
  backend_python:
    driver: bridge
